Issue 138: Add system arch diagram and update README.md
OMSCentral/omscentral pull request #153
Opened 2021-06-27 16:21 UTC by ghormadesoham

Issue 138: Add system arch diagram and update README.md

2021-08-09 22:42 UTC, mehmetbajin commented on README.md
> +
These lines should be deleted as they duplicate lines 1-18.

2021-08-09 22:42 UTC, mehmetbajin commented on README.md
> +When finished, users created during tests may be cleaned up using this script.
These lines should also be deleted as they duplicate existing content.

2021-08-09 22:43 UTC, mehmetbajin commented on README.md
> +## System Architecture overview
nit: Please include an empty line after section headers.

2021-08-09 22:43 UTC, mehmetbajin commented on README.md
> +- The client allows an authenicated user(see User Authenication section ) to add or delete reviews or an modify existing review for a course.
nit: Whitespace issue.

2021-08-09 22:44 UTC, mehmetbajin commented on README.md
> +- The client allows an authenicated user(see User Authenication section ) to add or delete reviews or an modify existing review for a course.
nit: Content can be better like so:

```
- The client is a React single-page-application that allows users to see anonymous reviews.
- Authenticated users may also publish, edit, or delete reviews (that they own) for the courses.
```

2021-08-09 22:46 UTC, mehmetbajin commented on README.md
> +- Frameworks used: Google [material-ui](https://material-ui.com/)
We should also list:
- apollo here as the GraphQL client library
- sentry for capturing client-side errors, logging
- eslint for build time linting, static analysis
- firebase for deployment
- graphql for client/server communication protocol
- prettier for code formatting
- react-hook-form for creating forms

2021-08-09 22:46 UTC, mehmetbajin commented on README.md
> +- The server persists course reviews and semester information to the database(See Persistence section below).
nit: The server is also responsible for updating the aggregations and statistics for courses such as average rating, average workload, etc.

2021-08-09 22:47 UTC, mehmetbajin commented on README.md
> +- Frameworks used: Node.js based [express](https://expressjs.com/)
Take a look at server's package.json for other libraries that are relevant.

2021-08-09 22:47 UTC, mehmetbajin commented on README.md
> +- The courses, semesters and reviews data is stored in a  relational database.
nit: Whitespace issue (double spaces).

2021-08-09 22:47 UTC, mehmetbajin commented on README.md
> +- The server reads and writes to postgres database using [graphql](https://graphql.org/).
This is incorrect. The server reads/writes to postgres DB using objection js and knex js.

2021-08-09 22:48 UTC, mehmetbajin commented on README.md
> +- Tools used: Google [Firebase](https://firebase.google.com/)
We should deep link to Google's Firebase Web Authentication page.

2021-08-09 22:49 UTC, mehmetbajin requested changes
Mostly nits!

2021-08-10 23:14 UTC, ghormadesoham commented on README.md
> +
This was a copy paste error.
Good catch, will fix.

2021-08-11 00:32 UTC, ghormadesoham commented on README.md
> +- The courses, semesters and reviews data is stored in a  relational database.
Given that the usual code formatting in VSCode does not work for markdown documents, I installed this [extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to fix the formatting errors.
This will help in catching and fixing other formatting issues.

2021-08-11 00:45 UTC, ghormadesoham commented on README.md
> +- Tools used: Google [Firebase](https://firebase.google.com/)
I found this [link](https://firebase.google.com/docs/auth/web/start) when I googled for " Google's Firebase Web Authentication". I am assuming you are referring to the same link.
Let me know if this not the case, thanks!

2021-08-11 00:49 UTC, ghormadesoham commented on README.md
> +
Fixed!

2021-08-11 00:49 UTC, ghormadesoham commented on README.md
> +When finished, users created during tests may be cleaned up using this script.
Good catch. Fixed!

2021-08-11 00:51 UTC, ghormadesoham commented on README.md
> +- Frameworks used: Node.js based [express](https://expressjs.com/)
Thanks for the tip, Mehmet.
Specifically, as an update, 
- the documentation i.e the markdown documentation also includes the link to packages.json inside the repo for server and client respectively.
- the documentation has been updated to include the list of other dependencies.

2021-08-11 00:51 UTC, ghormadesoham commented on README.md
> +- The server reads and writes to postgres database using [graphql](https://graphql.org/).
Good catch. Fixed!

2021-08-11 00:54 UTC, ghormadesoham commented on README.md
> +- The client allows an authenicated user(see User Authenication section ) to add or delete reviews or an modify existing review for a course.
@mehmetbajin, thank you for reviewing my PR and providing feedback.

As an update, from my end, this PR has been updated and the comments which have been addressed have been resolved.
From your end, given that update, please take a second look.
Thanks!

2021-08-11 00:55 UTC, ghormadesoham commented on README.md
> +- updates the  statistics for courses
self nit: spacing

2021-08-12 02:02 UTC, merged