Updates to coursers and OMSA
OMSCentral/omscentral pull request #228
Opened 2022-03-12 16:00 UTC by driscoll42

This is to resolve bugs https://github.com/OMSCentral/omscentral/issues/209 And https://github.com/OMSCentral/omscentral/issues/205

2022-04-13 21:14 UTC, mehmetbajin commented on server/database/data/courses.ts
> +    deprecated: false,
Given there's already a Privacy for Professionals course, what is the motivation for adding this one?

2022-04-13 21:16 UTC, mehmetbajin requested changes

2022-04-13 21:16 UTC, mehmetbajin commented on server/database/data/courses.ts
> +  },
Can you provide more context on VIP-6600? The link is unlike the other courses.

2022-04-13 21:16 UTC, mehmetbajin commented on server/database/data/specializations.ts
> +		  'CS-6603',
Please run `npm run format` (inside `./server` director) to ensure the whitespace is properly formatted.

2022-04-16 21:51 UTC, driscoll42 commented on server/database/data/courses.ts
> +  },
It is different from all the other courses. VIP (Vertically Integrated Projects) are not normal courses with lectures/homework/projects/exams, instead they are multidisciplinary projects you work on for credit lead by faculty. It's more like a typical work project, where you meet weekly as a group with the faculty member to discuss progress, problems, next steps, etc... 

In the case of the one I'm in, it's part of the Ivan Allen Digital Archive (http://allenarchive.iac.gatech.edu/) where we are working on making the website more accessible/usable, specifically for myself I am working on linking all the tags on the documents to Wikipedia articles, as well as improving the quality of the tags, with a combination of NLP/NER and some models trained to detect appropriate articles for tags.

Personally I think having this "course" on OMSCentral would be highly valuable as there's relatively little visibility into the program, hard to find people with experience in it, and having it on OMSCentral would help draw attention to it, let people talk about their time in it, and it is a course you get credit for on OMSCS, like any of the other traditional ones.

2022-04-16 21:55 UTC, driscoll42 commented on server/database/data/courses.ts
> +    deprecated: false,
I was searching for the number, not the title, looks like the number has changed, I'll remove this one.

2022-04-16 22:03 UTC, driscoll42 commented on server/database/data/specializations.ts
> +		  'CS-6603',
I think it's corrected now

2022-04-23 17:14 UTC, mehmetbajin approved these changes

2022-04-23 17:20 UTC, merged