Filter courses by alias
OMSCentral/omscentral pull request #28
Opened 2020-10-26 00:01 UTC by aadams94

This commit hopefully closes #9 without adding any bugs. It added an alias for every course (or duplicates course name where an alias does not exist). New migration was added and an additional filter using the alias was added. 
It then makes it possible to filter courses by alias eg 'GA' for 'Graduate Algorithms'.

2020-10-26 19:04 UTC, mehmetbajin requested changes
Please rename `alias` to `aliases` since the value is a collection of aliases rather than a single alias.

2020-10-26 19:04 UTC, mehmetbajin commented on server/src/models/Course.ts
> +      alias: { type: 'array' },
```
{ type: 'array', items: { type: 'string' } },
```

2020-10-26 19:04 UTC, mehmetbajin commented on client/src/components/Routes/components/Courses/Courses.tsx
>          [course.id, course.department, course.name]
We can just append the aliases to this input array instead:

```
[course.id, course.department, course.name, ...course.aliases]
```

2020-10-26 19:04 UTC, mehmetbajin commented on graphql/schema.graphql
> +  alias: [String]!
This should be typed as a not-null list of not-null Strings:

```
[String!]!
```

2020-11-01 15:58 UTC, aadams94 commented
Requested changes effected.

2020-11-01 16:04 UTC, mehmetbajin requested changes

2020-11-01 16:04 UTC, mehmetbajin commented on server/database/migrations/20191116001010_create_table_course.ts
> +    tb.jsonb('aliases').notNullable().defaultTo([]);
Migrations that have already run in production should not be modified.

2020-11-01 16:04 UTC, mehmetbajin commented on client/src/components/Routes/components/Courses/components/Toolbar/Toolbar.tsx
> +        label="Filter Courses (eg CS-6515 or GA or Graduate Algorithms)"
What is the motivation for this change?

2020-11-01 16:04 UTC, mehmetbajin commented on server/src/models/Course.ts
> +  aliases!: Array<string>;
nit: prefer `string[]` (shorter)

2020-11-01 19:53 UTC, aadams94 commented on client/src/components/Routes/components/Courses/components/Toolbar/Toolbar.tsx
> +        label="Filter Courses (eg CS-6515 or GA or Graduate Algorithms)"
This is to let the user know the options for filtering. For example, the user knows to filter using 'CS-6515' instead of 'CS 6515'. Beyond that, it is of no real significance.

2020-11-01 20:12 UTC, aadams94 commented on server/database/migrations/20191116001010_create_table_course.ts
> +    tb.jsonb('aliases').notNullable().defaultTo([]);
Ok, that's right. 
But if one were to start afresh (eg setting up the dev environment on a new computer) and one creates the omscentral_scratch database and runs the migrations, the following error is produced: 
"migration file "20191116010010_update_table_course.ts" failed 
... column omscentral_course.aliases does not exist
"
What is the best solution to this without modifying migration files?

2020-11-01 20:18 UTC, aadams94 commented on server/src/models/Course.ts
> +  aliases!: Array<string>;
Updated

2020-11-02 00:02 UTC, mehmetbajin commented on server/database/migrations/20191116001010_create_table_course.ts
> +    tb.jsonb('aliases').notNullable().defaultTo([]);
When I create a new migration that is a copy of the `***_update_table_course.ts` migration in this PR and attempt running the migrations on a brand new database, I do not observe any errors:

```
➜  server git:(staging) npm run knex migrate:make update_table_course

> omscentral-server@0.0.0 knex ~/Documents/github/omscentral/server
> knex --knexfile database/knexfile.ts "migrate:make" "update_table_course"

Requiring external module ts-node/register
Working directory changed to ~/Documents/github/omscentral/server/database
Created Migration: ~/Documents/github/omscentral/server/database/migrations/20201101185957_update_table_course.ts
➜  server git:(staging) ✗ psql
psql (12.4)
Type "help" for help.

bajin=# create database omscentral_scratch2
bajin-# ;
CREATE DATABASE
bajin=# ^D\q
➜  server git:(staging) ✗ npm run knex migrate:latest

> omscentral-server@0.0.0 knex ~/Documents/github/omscentral/server
> knex --knexfile database/knexfile.ts "migrate:latest"

Requiring external module ts-node/register
Working directory changed to ~/Documents/github/omscentral/server/database
Batch 1 run: 20 migrations
➜  server git:(staging) ✗ 
```

2020-11-02 00:06 UTC, mehmetbajin commented on client/src/components/Routes/components/Courses/components/Toolbar/Toolbar.tsx
> +        label="Filter Courses (eg CS-6515 or GA or Graduate Algorithms)"
The long label results in wrapping:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/10424048/97819247-58b5e880-1c75-11eb-9113-ce84caf45879.png">

Please revert this change.

2020-11-02 07:43 UTC, aadams94 commented on client/src/components/Routes/components/Courses/components/Toolbar/Toolbar.tsx
> +        label="Filter Courses (eg CS-6515 or GA or Graduate Algorithms)"
Reverted in 65bcdeaf76328b4fc81d118617ec5d4dc6041136

2020-11-02 07:44 UTC, aadams94 commented on server/src/models/Course.ts
> +  aliases!: Array<string>;
63890552f1812f32d620395a6e609f0351514971

2020-11-02 07:56 UTC, aadams94 commented on server/database/migrations/20191116001010_create_table_course.ts
> +    tb.jsonb('aliases').notNullable().defaultTo([]);
I see. In my comment above, i was referring to the case after updating /server/database/data/courses.ts to include the aliases and creating a migration to add an 'aliases' column. 
Running migrate:latest on a newly created database will give the error i mentioned. 
Maybe the 'aliases' data will have to go into a new file instead of .../database/data/courses.ts

2020-11-05 14:19 UTC, mehmetbajin commented on server/database/migrations/20191116001010_create_table_course.ts
> +    tb.jsonb('aliases').notNullable().defaultTo([]);
I'm still unable to repro any errors in this scenario.

2020-11-05 14:29 UTC, mehmetbajin commented
implemented in https://github.com/OMSCentral/omscentral/commit/a9c307d07e73efbbf932a054a4250472c49af8ae

2020-11-05 14:29 UTC, closed without merging