E2E (Cypress) for review update flow
OMSCentral/omscentral pull request #68
Opened 2021-01-04 22:36 UTC by burak-turk

I created the end-to-end testing for review update flow. It follows a similar pattern that other tests have.

2021-01-09 20:57 UTC, mehmetbajin requested changes
As part of this PR, can we refactor `create.spec.ts` such that the `beforeEach` that creates a review uses the new `omsCreateReview` cypress command for the review creation?

2021-01-09 20:57 UTC, mehmetbajin commented on client/src/components/ReviewCard/ReviewCard.tsx
> +              data-cy={'review_card_' + tooltip.toLocaleLowerCase()}
It's nice having the dynamic `data-cy` attribute; however, the attribute is now tightly coupled to the tooltip text.

This means any time the tooltip changes, cypress will break (not good).

Can we instead decouple the two? This way, the tooltip can continue to evolve over time without regressing cypress.

I think the best way to do this is to update the `chips` collection such that each element in the collection includes a unique `dataCy` property:

```typescript
  const chips: Array<ChipProps & { tooltip: string, dataCy: string }> = [
    {
      className: (classes as any)[`difficulty${d}`],
      label: difficulty,
      tooltip: 'Difficulty',
      dataCy: 'review_card_difficulty',
    },
    {
      className: (classes as any)[`rating${r}`],
      label: rating,
      tooltip: 'Rating',
      dataCy: 'review_card_rating',
    },
    {
      label: workload,
      tooltip: 'Workload',
      dataCy: 'review_card_workload',
    },
  ].filter((chip) => Boolean(chip?.label));
  xs && chips.pop() && chips.pop();
```

Then, we can do:

```typescript
{chips.map(({ tooltip, label, dataCy, ...rest }) => (

)}
```

2021-01-09 20:57 UTC, mehmetbajin commented on client/cypress/support/index.d.ts
> +    ): Cypress.cy;
This is a useful api, thanks for creating it.

One potential concern is the long list of parameters. Can we instead pass around objects instead of a parameter list of primitives?

Something like this:

```typescript
omsCreateReview(review: ReviewInputType): Cypress.cy;
```

We can import the `ReviewInputType` type from the auto-generated graphql artifacts:

```typescript
import { ReviewInputType } from '../../src/graphql';
```

For reference, this is what `ReviewInputType` looks like:

```typescript
export type ReviewInputType = {
  id: Scalars['String'];
  author_id: Scalars['String'];
  course_id: Scalars['String'];
  semester_id: Scalars['String'];
  difficulty: Scalars['Int'];
  rating: Scalars['Int'];
  workload: Scalars['Float'];
  body: Scalars['String'];
};
```

2021-01-09 20:57 UTC, mehmetbajin commented on client/cypress/fixtures/review.ts
> +export interface TestReview {
Instead of introducing a new custom interface, I wonder if we can reuse `ReviewInputType` from `src/graphql/index.tsx` instead? 

That way, the test code also consumes GraphQL types, which would promote reuse and modularity.

2021-01-09 20:57 UTC, mehmetbajin commented on client/cypress/fixtures/review.ts
> +export const testReview2: TestReview = {
I've found that naming variables `foo1`, `foo2` is generally an anti-pattern, because it makes the intent of the code less clear.

For instance, looking at the symbols exported from this file, even knowing that the context is "dummy data for testing", I don't have a good handle on why I would want to use `testReview1` vs. `testReview2` vs. create a new export named `testReview3`, 4, 5, etc.

Can you describe the problem we are able to solve using the hard-coded test reviews here?

2021-01-09 23:38 UTC, burak-turk commented on client/src/components/ReviewCard/ReviewCard.tsx
> +              data-cy={'review_card_' + tooltip.toLocaleLowerCase()}
Sounds good! I will make these changes.

2021-01-09 23:39 UTC, burak-turk commented on client/cypress/support/index.d.ts
> +    ): Cypress.cy;
This approach will make it a lot cleaner. I will modify the code.

2021-01-09 23:40 UTC, burak-turk commented on client/cypress/fixtures/review.ts
> +export interface TestReview {
Great point, I will use the existing one👍

2021-01-09 23:45 UTC, burak-turk commented on client/cypress/fixtures/review.ts
> +export const testReview2: TestReview = {
I added those to use anytime a test review data is needed. They are kind of similar to the user object under user.ts. Create integration test can use it.  When we develop delete integration test, it could use it too. However, I see your point. I am open to getting rid of them or suggestions to adress the same problem in a different way. Let me know!

2021-01-09 23:46 UTC, burak-turk commented
> As part of this PR, can we refactor `create.spec.ts` such that the `beforeEach` that creates a review uses the new `omsCreateReview` cypress command for the review creation?

I was thinking the same. I will refactor the create integration test to utilize the new command.

2021-01-10 18:57 UTC, mehmetbajin commented on client/cypress/fixtures/review.ts
> +export const testReview2: TestReview = {
Can we introduce an api that serves the following request from a consumer instead?

> Hey, api, I need a dummy review object for my test run. Can you give me one that I can use for XYZ-ing a review?

Here, the XYZ operation could be _create_, _update_, or _delete_. 

In code, one way we could do this:

```typescript
export const getTestReview = (): ReviewInputType => {
  // ...
};
```

2021-01-10 19:39 UTC, burak-turk commented on client/src/components/ReviewCard/ReviewCard.tsx
> +              data-cy={'review_card_' + tooltip.toLocaleLowerCase()}
Done!

2021-01-10 19:39 UTC, burak-turk commented on client/cypress/support/index.d.ts
> +    ): Cypress.cy;
Done!

2021-01-10 19:39 UTC, burak-turk commented on client/cypress/fixtures/review.ts
> +export interface TestReview {
Done!

2021-01-10 19:40 UTC, burak-turk commented on client/cypress/fixtures/review.ts
> +export const testReview2: TestReview = {
I got rid of this completely as I don't think it add enough value. We can consider creating an API for it in the future if we end up needing it.

2021-01-10 19:41 UTC, burak-turk commented
> > As part of this PR, can we refactor `create.spec.ts` such that the `beforeEach` that creates a review uses the new `omsCreateReview` cypress command for the review creation?
> 
> I was thinking the same. I will refactor the create integration test to utilize the new command.

Done!

2021-01-11 14:26 UTC, mehmetbajin reviewed
We expanded the considerations in this iteration, and now we have an opportunity to integrate once again. The quality of the tests are improving significantly with each iteration, and we are very close!

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/create.spec.ts
> +    };
This is awesome. It's generally a good idea to avoid using `const` objects in tests. This is because cypress does not re-initialize the variable from one test run to another.

Instead, we can declare `review` as with `let` first:

```typescript
let review: ReviewInputType;
```

...and then in the `beforeEach`, we can initialize it:

```typescript
beforeEach(() => {
  review = {
    // ...
  };
});
```

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/create.spec.ts
> +      cy.url().should('match', new RegExp('/course/' + review.course_id + '$'));
In this case, the linter warning is safe to ignore; however, we can at least use a sting template literal to improve readability:

```typescript
      cy.url().should('match', new RegExp(`/course/${review.course_id}$`));
```

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +import { test } from 'mocha';
Is this line needed?

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +  const review_initial: ReviewInputType = {
Same consideration as the create.spec.ts test with respect to `const` vs. `let` applies here.

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +  describe('when the course reviews page is displayed', () => {
Can we continue the `given / when / then` pattern for the test names and descriptions that we see in other *.spec.ts files? It requires some grammatical gymnastics, but the consistency helps with reducing complexity.

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +  describe('when the course reviews page is displayed', () => {
This `describe` block is actually testing something related but different than the other `describe` block on line 57. 

Specifically, this first block is testing the behavior of the application on a review list view. The next block is actually testing the update behavior. These two behaviors, while related, can and should be tested independently.

Could we separate these into distinct files instead of overloading one file with multiple concerns?

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +        .within(() => cy.dataCy('review_card_edit_button').click());
It seems this "navigate to edit review page" command is repeatedly used throughout the tests. Can we extract it out into a common command similar to `omsGoToCreateReview`? 

We could name it `omsGoToUpdateReview` and it would by default navigate to the reviews list view and then click the Edit button for the first review. In the future, we could extend the API to configure which review's Edit button is clicked, for example.

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +      cy.dataCy('review_submit').click();
Similarly, this is now another set of operations that is repeated across tests. Namely, the command of "populate the review form with this `ReviewInputType` object's data" -- can it be extracted into a common command?

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +        new RegExp('/course/' + review_updated.course_id + '$'),
You can tell the linter "I know what I'm doing" by adding:

```typescript
// eslint-disable-next-line <rule_id>
// <-- this is the line with the linter warning
```

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/support/commands.js
> +Cypress.Commands.add('omsCreateReview', (review) => {
At first glance, the API seems like something I can call just from any test to create a review. Except that's not completely accurate.

Upon closer inspection, we see there is a precondition that must be met for this API to succeed. Specifically, the user must be on the "Create Review" page. 

Can we bring the code that satisfies the precondition within this API? This way, the public interface of the API can actually become "call me from any test to create a review". 

The code in question is:

```typescript
    cy.omsGoTo('/login')
      .omsLogin(user.email, user.password)
      .omsGoToCreateReview();
```

This introduces additional considerations, however. Now, the caller must ensure that the user is logged out _before consuming the API_. One way we can accommodate this with flexibility is to expose an `options` parameter in the API function signature:

```typescript
.add('omsCreateReview', (review, options) => {
  // ...
});
```

`options` could be something like:

```typescript
{
  authenticate: boolean
}
```

If `authenticate` is true, the API would first navigate to `/login` page and log the user in. Otherwise, the API would skip that step. In both cases, after login (or after skipping the login operation), the API would navigate the user to the Create Review page with `.omsGoToCreateReview()`.

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/support/commands.js
> +        workload + ' hrs/wk',
nit: Prefer string template literals here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/support/commands.js
> +Cypress.Commands.add('omsCheckReview', (review) => {
nit: rename api to `omsCheckReviewCard`

2021-01-11 14:26 UTC, mehmetbajin commented on client/cypress/support/commands.js
> +  const rating = reviewMeta.translateRating(review.rating);
nit: some assertions inline the `review.<whatever>` while others declare `const`'s up here. Can we stick to one convention for simplicity?

2021-01-12 07:16 UTC, burak-turk commented on client/cypress/integration/review/create.spec.ts
> +    };
Done!

2021-01-12 07:23 UTC, burak-turk commented on client/cypress/integration/review/create.spec.ts
> +      cy.url().should('match', new RegExp('/course/' + review.course_id + '$'));
👍

2021-01-12 07:23 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +import { test } from 'mocha';
No it isn't. Removed.

2021-01-12 07:25 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +  const review_initial: ReviewInputType = {
👍

2021-01-12 07:27 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +  describe('when the course reviews page is displayed', () => {
I did some changes but I am not sure if they are aligned with what you are looking for. If more changes are needed, I will need more details :)

2021-01-12 07:28 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +  describe('when the course reviews page is displayed', () => {
Great idea, I broke them into two tests.

2021-01-12 07:28 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +        .within(() => cy.dataCy('review_card_edit_button').click());
Done!

2021-01-12 07:29 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +      cy.dataCy('review_submit').click();
Good point, I created a custom command for this set of actions.

2021-01-12 07:29 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +        new RegExp('/course/' + review_updated.course_id + '$'),
👍

2021-01-12 07:29 UTC, burak-turk commented on client/cypress/support/commands.js
> +Cypress.Commands.add('omsCreateReview', (review) => {
Great call out! I made the changes.

2021-01-12 07:29 UTC, burak-turk commented on client/cypress/support/commands.js
> +        workload + ' hrs/wk',
👍

2021-01-12 07:29 UTC, burak-turk commented on client/cypress/support/commands.js
> +Cypress.Commands.add('omsCheckReview', (review) => {
👍

2021-01-12 07:30 UTC, burak-turk commented on client/cypress/support/commands.js
> +  const rating = reviewMeta.translateRating(review.rating);
I got rid of the `const`'s as they aren't needed anymore.

2021-01-14 20:29 UTC, mehmetbajin requested changes
Functionally, things look good.

We have areas for improving the code quality.

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/create.spec.ts
> +      };
Unlike `review`, `createReviewOptions` is not re-referenced outside of this callback. 

Can we inline `createReviewOptions` instead of maintaining it in a variable to reduce complexity?

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/create.spec.ts
> +      };
This also applies to the update.spec.ts file below.

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/edit.button.spec.ts
> +    it(`then Review page is displayed in update mode`, () => {
nit: `then displays the Review in update mode`

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/edit.button.spec.ts
> +/// <reference path="../../support/index.d.ts" />
nit: rename file to `edit-button.spec.ts` (prefer using dots only in the `.spec.ts` extension)

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +  let review_initial: ReviewInputType;
nit: prefer `camelCase` to `snake_case` with variables

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +    let review_updated: ReviewInputType;
nit: prefer `camelCase` to `snake_case` with variables

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/update.spec.ts
> +        // eslint-disable-next-line security/detect-non-literal-regexp
As I think about this more, I think we can disable this rule completely across all cypress code, what do you think?

That way we don't have to keep introducing `eslint-disable-next-line` all over the place.

You can globally disable by updating `client/cypress/.eslintrc.js`.

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/support/commands.js
> +Cypress.Commands.add('omsPopulateReviewAndSubmit', (review) => {
Can we separate these into two commands?

* `omsPopulateReview`
* `omsSubmitReview`

Then, anywhere `omsPopulateReviewAndSubmit` is called would call the above two methods in order.

This way, we have flexibility in the future to do one without the other (if needed).

2021-01-14 20:29 UTC, mehmetbajin commented on client/cypress/integration/review/edit.button.spec.ts
> +    cy.dataCy('sort_by_created').click({ force: true }).wait(1000);
Before, this line appeared in the codebase exactly once.

Now, it has been copy/pasted into multiple places. How can we avoid repeating identical code like this?

2021-01-14 23:17 UTC, burak-turk commented on client/cypress/integration/review/edit.button.spec.ts
> +    cy.dataCy('sort_by_created').click({ force: true }).wait(1000);
I moved it `omsSubmitReview` as this action is needed after submitting a review.

2021-01-14 23:17 UTC, burak-turk commented on client/cypress/support/commands.js
> +Cypress.Commands.add('omsPopulateReviewAndSubmit', (review) => {
👍

2021-01-14 23:17 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +        // eslint-disable-next-line security/detect-non-literal-regexp
I agree, removed the lines and added as a rule to `client/cypress/.eslintrc.js`.

2021-01-14 23:17 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +    let review_updated: ReviewInputType;
👍

2021-01-14 23:17 UTC, burak-turk commented on client/cypress/integration/review/update.spec.ts
> +  let review_initial: ReviewInputType;
👍

2021-01-14 23:17 UTC, burak-turk commented on client/cypress/integration/review/edit.button.spec.ts
> +/// <reference path="../../support/index.d.ts" />
👍

2021-01-14 23:18 UTC, burak-turk commented on client/cypress/integration/review/edit.button.spec.ts
> +    it(`then Review page is displayed in update mode`, () => {
👍

2021-01-14 23:18 UTC, burak-turk commented on client/cypress/integration/review/create.spec.ts
> +      };
👍

2021-01-16 17:20 UTC, mehmetbajin approved these changes

2021-01-16 17:20 UTC, merged