filter sort improvements
OMSCentral/omscentral pull request #87
Opened 2021-02-24 08:56 UTC by burak-turk

2021-03-05 14:01 UTC, mehmetbajin commented
This is much better.

Code review is difficult, because the PR is very large. One thing that would make code review more efficient is breaking up the PR into atomic commits, each one incrementally introducing a change. Could you break up this PR into multiple commits instead of just 1? Try to keep a commit to 25-50 LOC added/deleted/edited.

2021-03-06 07:29 UTC, burak-turk commented
> This is much better.
> 
> Code review is difficult, because the PR is very large. One thing that would make code review more efficient is breaking up the PR into atomic commits, each one incrementally introducing a change. Could you break up this PR into multiple commits instead of just 1? Try to keep a commit to 25-50 LOC added/deleted/edited.

Thanks for the feedback, Mehmet! I broke it up into 16 commits and I gave them a logical order. I hope the changes will make sense as you review them one by one.

2021-03-17 17:03 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/ToolbarButton/ToolbarButton.styles.ts
> +  toolbarButton: {
The file is already named ToolbarButton, so we don't have to repeat the name here.

How about `button` instead?

2021-03-20 20:46 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  useEffect(() => {
Could you explain what is happening in this `useEffect` and the one after?

I'm trying to understand why `useEffect` is needed here. Generally, `useEffect` should be reserved for responding to events that occur outside the React context.

2021-03-20 20:46 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  const determineYearState = (
What is this function doing?

2021-03-20 20:47 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  >({});
Instead of a plain object, can we use the more strongly typed `Map`?

`useState<Map<...>>(...)`

2021-03-20 20:48 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  semesters: Record<string, boolean>;
Again, can we use `Map` instead of `Record`?

2021-03-20 20:48 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +    <>
Why are we wrapping the single child in a fragment here?

2021-03-20 20:49 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  useEffect(() => {
Why is `useEffect` needed here?

2021-03-20 20:50 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  };
These kinds of utility functions should be declared _outside_ the component body for performance.

2021-03-20 20:50 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> -  } = useModalState(false);
Why `useState` instead of `useModalState`?

2021-03-20 20:56 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/FilterMenu/FilterMenu.tsx
> +        }`}
Please extract this complex logic out into a utility function declared just outside this component body.

2021-03-20 20:56 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +              sortKeyOptions.find((option) => option.value === sortKey)?.label
Since `sortKey` is guaranteed to appear in `sortKeyOptions`, can we use `!` instead of `?`?

2021-03-20 20:57 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/AutocompleteFilter/AutocompleteFilter.tsx
> +  }, [options, initialValue]);
Why is `useEffect` needed?

2021-03-20 20:57 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> -
Why is this being removed?

2021-03-20 20:58 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +    {},
Use `Map` instead of `Record`, please. `Map`'s keys are typed while a `Record`'s keys are always strings.

2021-03-20 20:58 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  const calculateFilterCount = (
What is this function doing?

2021-03-20 20:59 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +type SemesterYear = {
What is the purpose of this type?

2021-03-20 20:59 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +type SemesterFilterState = {
What is the purpose of this type?

2021-03-20 20:59 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  semesterFilterOptions: SemesterOption[];
Rename this to `options`, since "semester filter" already appears in the component name.

2021-03-20 20:59 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  onSubmit: (semester_ids: string[]) => void;
Replace `semester_ids` with `semesterIds` please. snake_case should be reserved for graphql only.

2021-03-20 21:00 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +              {
Why are the braces needed here?

2021-03-20 21:01 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        }
I understand what `checked` is, but I am having trouble understanding how its boolean value is looked up. 

Can you explain the data structure here and how state is managed?

2021-03-20 21:02 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        }
Similar to the comment below, I'm having trouble understanding the data structure being used to manage state here. Can you explain what is happening?

2021-03-20 21:02 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        id={semesterYear.year}
Is year guaranteed to not repeat?

2021-03-20 21:03 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        className={`${classes.filterCheckbox} ${classes.filterCheckboxSub}`}
Please use `clsx` for joining class names.

2021-03-20 21:03 UTC, mehmetbajin commented on client/src/core/types/SemesterOption.ts
> +export type SemesterOption = Option & {
Why is this custom type necessary?

2021-03-20 21:04 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  const determineSemesterState = (
What is this function doing?

2021-03-20 21:04 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.container.tsx
> +  let semesterFilterOptions: SemesterOption[] =
Why is `let` needed here?

2021-03-22 05:11 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +    <>
It eventually contains three children. I should have kept the wrapper out of this commit and included in the `semesterfilter component - part 4: add filterbuttontray to show clear and apply buttons` as it increases the number of children from one to three.

2021-03-22 06:06 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  useEffect(() => {
The first one takes the semesters from `semesterFilterOptions` and transforms it into a nested structure called `semesterYears`, which is used by the component to show semesters as grouped by year. 

The second one sets the initial state for `semesterFilters`, which is used to tracked checked/unchecked state of the semesters.

I did take a look at both of them and you are right, `useEffect` isn't needed for both of them. In fact, `semesterYears` doesn't even need to be a state. I made changes to address these. Please see [224d08f](https://github.com/OMSCentral/omscentral/pull/87/commits/224d08fab07bed1bb48c7d24ecf53f20221d1f33).

2021-03-22 06:07 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  semesterFilterOptions: SemesterOption[];
Done with [224d08f](https://github.com/OMSCentral/omscentral/pull/87/commits/224d08fab07bed1bb48c7d24ecf53f20221d1f33).

2021-03-22 06:08 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  onSubmit: (semester_ids: string[]) => void;
Done with [224d08f](https://github.com/OMSCentral/omscentral/pull/87/commits/224d08fab07bed1bb48c7d24ecf53f20221d1f33).

2021-03-22 06:08 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +              {
Removed with [224d08f](https://github.com/OMSCentral/omscentral/pull/87/commits/224d08fab07bed1bb48c7d24ecf53f20221d1f33).

2021-03-22 06:09 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        className={`${classes.filterCheckbox} ${classes.filterCheckboxSub}`}
Done with [224d08f](https://github.com/OMSCentral/omscentral/pull/87/commits/224d08fab07bed1bb48c7d24ecf53f20221d1f33).

2021-03-23 05:32 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  const determineYearState = (
This function determines state of a year checkbox. There are three possible states for a year:

1. Unchecked: Semesters under the year are unchecked.
2. Indeterminate: At least one but not all of the semesters under the year are checked.
3. Checked: All of the semesters under the year are checked.

`determineYearState` takes an object in `SemesterFilterState` type, goes through its semester states and updates values for the `checked` and `indeterminate` keys and returns it.

2021-03-23 05:38 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  const determineSemesterState = (
When a year checkbox is checked, all of the semester checkboxes under it should be set to checked. Similarly, if it is unchecked, they should be set to unchecked. When a user clicks on a year, `handleYearChange` updates the state for the year and `determineYearState` to update the year's semester states accordingly. The function basically goes through the semester states and sets them equal to the year state.

2021-03-23 06:51 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  const calculateFilterCount = (
It calculates the number of selected items and total items. `filterCounts`, which is later used to show number of selected items or "All" for the filters, is populated by utilizing this function.

2021-03-23 06:54 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +    {},
Done, please see [fcd486d](https://github.com/OMSCentral/omscentral/pull/87/commits/fcd486df37b47bf40a9241ba337be5d7e2f9b83d).

2021-03-23 06:55 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> -  } = useModalState(false);
I made changes to utilize `useModalState`. Please see [fcd486d](https://github.com/OMSCentral/omscentral/pull/87/commits/fcd486df37b47bf40a9241ba337be5d7e2f9b83d).

2021-03-23 06:55 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  useEffect(() => {
Good callout, not needed. Please see [fcd486d](https://github.com/OMSCentral/omscentral/pull/87/commits/fcd486df37b47bf40a9241ba337be5d7e2f9b83d) for the changes I made.

2021-03-23 06:56 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  };
I created a file called `Toolbar.utils.ts` and placed it there. Please see [fcd486d](https://github.com/OMSCentral/omscentral/pull/87/commits/fcd486df37b47bf40a9241ba337be5d7e2f9b83d).

2021-03-28 14:19 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  const determineYearState = (
Done is better than perfect, so for this pass, this is fine.

In the future, this kind of reusable behavior is an excellent candidate for a custom React hook or another component that can be dropped in to bring in such behavior to a parent component that needs it.

2021-03-28 14:22 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  const calculateFilterCount = (
OK, good to know.

2021-03-28 14:25 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  const determineSemesterState = (
Makes sense.

We can land this PR with the current client side architecture for the filters; however, a fast-follow that leverages React's `useReducer` hook will significantly reduce the complexity by decoupling the components from the business rules for managing the component state.

https://reactjs.org/docs/hooks-reference.html#usereducer

2021-03-28 14:26 UTC, mehmetbajin commented
@burak-turk The updates to the PR are excellent. There are still some outstanding comments; if you are able to at least take a quick pass for each to continue the conversation, that would help me understand your approach better. I think the PR is in a good enough state to land as is, and I'd appreciate your help with deepening my understanding of the approach.

2021-03-28 17:44 UTC, burak-turk commented
> @burak-turk The updates to the PR are excellent. There are still some outstanding comments; if you are able to at least take a quick pass for each to continue the conversation, that would help me understand your approach better. I think the PR is in a good enough state to land as is, and I'd appreciate your help with deepening my understanding of the approach.

Thank you for the feedback @mehmetbajin! I will get to all of the remaining ones this week. Bear with me, please :)

2021-04-12 07:09 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +type SemesterYear = {
It is the type for each year in the `semesterYears` array, which is used to render the nested year-semester filters.

2021-04-12 07:09 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +type SemesterFilterState = {
It is the type for each year in the `semesterFilters` state, which is used to maintain checked/unchecked state of the semester filters.

2021-04-12 07:17 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        }
A sample entry of `semesterFilters` looks like this:
```
key: "2021"
value: {
  checked: false,
  indeterminate: true,
  semesters: {
    "2021-1": false, 
    "2021-2": true, 
    "2021-3": false
  }
}
```
Each year has its semesters under the `semesters` key. This code block basically looks up the checked/unchecked state of the semester under the year.

2021-04-12 07:21 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        }
Using the same sample:
```
key: "2021"
value: {
  checked: false,
  indeterminate: true,
  semesters: {
    "2021-1": false, 
    "2021-2": true, 
    "2021-3": false
  }
}
```
Each year can have there states: checked (all of its semesters are checked), unchecked (none of its semesters are checked) or indeterminate (at least one but not all semesters are checked). The data structure maintains this with two boolean values: `checked` and `indeterminate` to match the Material-ui checkbox API.

2021-04-12 07:25 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +                        id={semesterYear.year}
Based on how data for `semesterYears` is created, yes. However, there is nothing enforcing it from type system standpoint. Do you think it should be enforced?

2021-04-12 07:28 UTC, burak-turk commented on client/src/core/types/SemesterOption.ts
> +export type SemesterOption = Option & {
In addition to `label` and `value` that comes with `Option` type, `year` and `season` are needed for the nested semester filter view.

2021-04-12 07:31 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.container.tsx
> +  let semesterFilterOptions: SemesterOption[] =
If the component is being loaded for a course page, the following code block removes the semesters that the course doesn't have reviews for. For this modification, I had to use `let`.

```
props.courseSemesters &&
    (semesterFilterOptions = semesterFilterOptions.filter((option) =>
      props.courseSemesters?.includes(option.value),
    ));
```

2021-04-12 08:51 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  >({});
Done. Please see [bfe2543](https://github.com/OMSCentral/omscentral/pull/87/commits/bfe2543a82fa8b756326cad5754484fb7287359e).

2021-04-12 08:51 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +  semesters: Record<string, boolean>;
Done. Please see [bfe2543](https://github.com/OMSCentral/omscentral/pull/87/commits/bfe2543a82fa8b756326cad5754484fb7287359e).

2021-04-12 08:51 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/FilterMenu/FilterMenu.tsx
> +        }`}
Please see [bfe2543](https://github.com/OMSCentral/omscentral/pull/87/commits/bfe2543a82fa8b756326cad5754484fb7287359e).

2021-04-12 08:51 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +              sortKeyOptions.find((option) => option.value === sortKey)?.label
Please see [bfe2543](https://github.com/OMSCentral/omscentral/pull/87/commits/bfe2543a82fa8b756326cad5754484fb7287359e).

2021-04-12 08:52 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/AutocompleteFilter/AutocompleteFilter.tsx
> +  }, [options, initialValue]);
Not needed. I removed it, please see [bfe2543](https://github.com/OMSCentral/omscentral/pull/87/commits/bfe2543a82fa8b756326cad5754484fb7287359e).

2021-04-12 08:52 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> -
Looks like I misunderstood what Grow was doing. I added back in. Please see [bfe2543](https://github.com/OMSCentral/omscentral/pull/87/commits/bfe2543a82fa8b756326cad5754484fb7287359e).

2021-04-12 08:54 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/SemesterFilter/SemesterFilter.tsx
> +type SemesterFilterState = {
It is the type for each year in `semesterFilters`, which holds checked/unchecked states of the checkboxes in the semester filter view.

2021-04-25 14:11 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.container.tsx
>  >;
You don't have to nest Omit within Omit, you can just do this instead:

![image](https://user-images.githubusercontent.com/10424048/115996739-8f2e4980-a5ae-11eb-849a-847d5a6fe73b.png)

2021-04-25 14:11 UTC, mehmetbajin commented on Procfile
> -web: cd server && npm run knex migrate:latest && npm start
Can you revert this?

2021-04-25 14:12 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.container.tsx
> +  let semesterFilterOptions: SemesterOption[] =
Can't we do something like this?

```
const semesterFilterOptions = getSemesterFilterOptions(...);
```

2021-04-25 14:13 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
>    };
Why is the argument of type `Option[]` for the course filter but the type for semester filter is `string[]`? 

I would expect them to be the same.

2021-04-25 14:13 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +      {semesterFilter && (
Should this be `semesterFilter != null`?

2021-04-25 14:14 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  semesterFilterOptions: SemesterOption[];
Why a new type -- `SemesterOption` -- for semesters?

What is fundamentally different about semester filters vs. course filters?

2021-04-25 14:15 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.utils.ts
> +  filters: string[] = [],
nit: Should this be renamed from `filters` to `selectedFilterValues`?

2021-04-25 14:17 UTC, mehmetbajin commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.utils.ts
> +  }
Would `filters` (to be renamed `selectedFilterValues`) ever include a value that is not in `filterOptions`?

2021-04-25 14:19 UTC, mehmetbajin commented on client/src/components/Routes/components/Course/Course.tsx
> +    courseSemesters={course.metric?.semesters}
`ReviewCardListConnected.container.tsx` is a container component. This means we can just update the behavior of the container to fetch the data needed for the components it contains.

In other words, a `*.container.tsx` component should not be receiving as input data that is fetched using GraphQL. The `*.container.tsx` component itself should be the one doing the fetching. 

Please preserve this architectural pattern instead of introducing a new pattern of fetching and passing data around.

2021-04-25 14:19 UTC, mehmetbajin commented on client/src/core/types/SemesterOption.ts
> +export type SemesterOption = Option & {
Why are `year` and `season` needed?

2021-04-25 14:19 UTC, mehmetbajin requested changes
Back to author.

2021-04-27 05:46 UTC, burak-turk commented on client/src/core/types/SemesterOption.ts
> +export type SemesterOption = Option & {
They are used for showing year and season values on the UI. Without them, we would have to extract them from `value` and `label` fields. This way, I tried to abstract it away from the UI component so that the data it receives is ready to be displayed to the end user.

2021-04-27 06:55 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +  semesterFilterOptions: SemesterOption[];
Related to [this comment](https://github.com/OMSCentral/omscentral/pull/87#discussion_r620883640)

2021-04-27 07:05 UTC, burak-turk commented on client/src/components/Routes/components/Course/Course.tsx
> +    courseSemesters={course.metric?.semesters}
I see what you are saying but `Course` already has the data. In fact, it uses it for the other two props of the `ReviewCardListConnected` component. Do we need to refetch it on `ReviewCardListConnected.container.tsx`?

2021-04-27 07:12 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.utils.ts
> +  }
Yes if the user enters a URL that contains a query for a semester that doesn't exist. For example: `/reviews?semester=2020-1&semester=2021-5`

2021-04-27 07:38 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.container.tsx
> +  let semesterFilterOptions: SemesterOption[] =
Done with [763a98a](https://github.com/OMSCentral/omscentral/pull/87/commits/763a98a158db72b61a4ccaffc82b624cc9fcc96a).

2021-04-27 07:38 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.container.tsx
>  >;
Done with [763a98a](https://github.com/OMSCentral/omscentral/pull/87/commits/763a98a158db72b61a4ccaffc82b624cc9fcc96a).

2021-04-27 07:39 UTC, burak-turk commented on Procfile
> -web: cd server && npm run knex migrate:latest && npm start
Done with [763a98a](https://github.com/OMSCentral/omscentral/pull/87/commits/763a98a158db72b61a4ccaffc82b624cc9fcc96a).

2021-04-27 07:39 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
> +      {semesterFilter && (
Done with [763a98a](https://github.com/OMSCentral/omscentral/pull/87/commits/763a98a158db72b61a4ccaffc82b624cc9fcc96a).

2021-04-27 07:39 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.utils.ts
> +  filters: string[] = [],
Done with [763a98a](https://github.com/OMSCentral/omscentral/pull/87/commits/763a98a158db72b61a4ccaffc82b624cc9fcc96a).

2021-04-27 15:31 UTC, burak-turk commented on client/src/components/ReviewCardListConnected/components/Toolbar/Toolbar.tsx
>    };
Done with [5157bf0](https://github.com/OMSCentral/omscentral/pull/87/commits/5157bf05f771ad9e2606736d29ee56af4c5c76b1)

2021-04-27 15:33 UTC, burak-turk commented
> Back to author.

Back to you @mehmetbajin :)

2021-04-30 01:07 UTC, mehmetbajin approved these changes

2021-04-30 01:08 UTC, merged